title: 우당탕탕 개발기록
email: hooney@example.com
description: 우당탕당 개발기록
author: Jay
baseurl: ''
url: 'https://jayhooney.github.io'

category_list: [nodejs, javascript, typescript]

# Social Profiles
twitter_username: leejaehoon__
github_username: jayhooney

# Add your google-analytics ID here to activate google analytics
google_analytics: UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown: kramdown
paginate: 5
paginate_path: '/posts/page:num/'
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
